name: CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  build-libcxx32:
    runs-on: macos-latest
    steps:
    - name: Check Cache libcxx32
      id: libcxx32-llvm
      uses: Mystraht/cache@master
      env:
        cache-name: cache-libcxx32-macos-10-10-2
      with:
        path: libcxx32-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx32
      if: steps.libcxx32-llvm.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx32-macos-10-10-2
      with:
        path: libcxx32-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.libcxx32-llvm.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Build libcxx, libcxxabi
      if: steps.libcxx32-llvm.outputs.cache-hit != 'true'
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.10.0
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        git clone https://github.com/llvm/llvm-project.git llvm
        mkdir -p libcxx32-build
        cd libcxx32-build
        cmake ../llvm/llvm -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" -DCMAKE_BUILD_TYPE=Release -DLIBCXX_BUILD_32_BITS=ON -DLIBCXXABI_BUILD_32_BITS=ON -DLLVM_BUILD_32_BITS=ON
        make -j4 cxx cxxabi
  build-libcxx64:
    runs-on: macos-latest
    steps:
    - name: Check Cache libcxx64
      id: libcxx64-llvm
      uses: Mystraht/cache@master
      env:
        cache-name: cache-libcxx64-macos-10-10-2
      with:
        path: libcxx64-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx64
      if: steps.libcxx64-llvm.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx64-macos-10-10-2
      with:
        path: libcxx64-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.libcxx64-llvm.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Build libcxx, libcxxabi
      if: steps.libcxx64-llvm.outputs.cache-hit != 'true'
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.10.0
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        git clone https://github.com/llvm/llvm-project.git llvm
        mkdir -p libcxx64-build
        cd libcxx64-build
        cmake ../llvm/llvm -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" -DCMAKE_BUILD_TYPE=Release
        make -j4 cxx cxxabi
  build-libcxx:
    runs-on: macos-latest
    needs: [build-libcxx32,build-libcxx64]
    steps:
    - name: Check libcxx
      id: libcxx-llvm
      uses: Mystraht/cache@master
      env:
        cache-name: cache-libcxx-macos-10-10-2
      with:
        path: libcxx-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx32
      if: steps.libcxx-llvm.outputs.cache-hit != 'true'
      id: libcxx32-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx32-macos-10-10-2
      with:
        path: libcxx32-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx64
      if: steps.libcxx-llvm.outputs.cache-hit != 'true'
      id: libcxx64-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx64-macos-10-10-2
      with:
        path: libcxx64-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx
      if: steps.libcxx-llvm.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx-macos-10-10-2
      with:
        path: libcxx-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Build universal lib
      if: steps.libcxx-llvm.outputs.cache-hit != 'true'
      run: |
        mkdir -p libcxx-build/
        lipo -create libcxx32-build/lib/libc++.dylib libcxx64-build/lib/libc++.dylib -output libcxx-build/libc++.1.dylib
        lipo -create libcxx32-build/lib/libc++abi.dylib libcxx64-build/lib/libc++abi.dylib -output libcxx-build/libc++abi.1.dylib
        cd libcxx-build
        ln -s libc++.1.dylib libc++.dylib
        ln -s libc++abi.1.dylib libc++abi.dylib
        install_name_tool -rpath @loader_path/../lib @loader_path/../Frameworks libc++.dylib
        install_name_tool -rpath @loader_path/../lib @loader_path/../Frameworks libc++abi.dylib
  brew-libzip:
    runs-on: macos-latest
    steps:
    - name: Check for libzip
      id: cache-brew-libzip
      uses: Mystraht/cache@master
      env:
        cache-name: cache-brew-libzip-macos-10-10
      with:
        path: /usr/local/Cellar/libzip
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libzip
      if: steps.cache-brew-libzip.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-libzip-macos-10-10
      with:
        path: /usr/local/Cellar/libzip
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.cache-brew-libzip.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Apply custom patch and Update brew
      if: steps.cache-brew-libzip.outputs.cache-hit != 'true'
      working-directory: "/usr/local/Homebrew"
      run: |
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git merge fork/master
    - name: Install brew dependencies
      if: steps.cache-brew-libzip.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.10.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall libzip
  brew-protobuf:
    runs-on: macos-latest
    steps:
    - name: Check for protobuf
      id: cache-brew-protobuf
      uses: Mystraht/cache@master
      env:
        cache-name: cache-brew-protobuf-macos-10-10
      with:
        path: /usr/local/Cellar/protobuf
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache protobuf
      if: steps.cache-brew-protobuf.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-protobuf-macos-10-10
      with:
        path: /usr/local/Cellar/protobuf
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.cache-brew-protobuf.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Apply custom patch and Update brew
      if: steps.cache-brew-protobuf.outputs.cache-hit != 'true'
      working-directory: "/usr/local/Homebrew"
      run: |
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git checkout fork/master
    - name: Install brew dependencies
      if: steps.cache-brew-protobuf.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install automake
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.10.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        brew reinstall python@3.8 || brew install python@3.8
        brew reinstall protobuf || brew install protobuf
  brew-libuv:
    runs-on: macos-latest
    steps:
    - name: Check for libuv
      id: cache-brew-libuv
      uses: Mystraht/cache@master
      env:
        cache-name: cache-brew-libuv-macos-10-10
      with:
        path: /usr/local/Cellar/libuv
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libuv
      if: steps.cache-brew-libuv.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-libuv-macos-10-10
      with:
        path: /usr/local/Cellar/libuv
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.cache-brew-libuv.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Apply custom patch and Update brew
      if: steps.cache-brew-libuv.outputs.cache-hit != 'true'
      working-directory: "/usr/local/Homebrew"
      run: |
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git checkout fork/master
    - name: Install brew dependencies
      if: steps.cache-brew-libuv.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install automake sphinx-doc
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.10.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        HOMEBREW_NO_AUTO_UPDATE=1 brew install libuv
  buildopenssl32:
    runs-on: macos-latest
    steps:
    - name: Check for openssl
      id: cache-openssl32
      uses: Mystraht/cache@master
      env:
        cache-name: cache-openssl32-macos-10-10
      with:
        path: /usr/local/ssl32
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache openssl
      if: steps.cache-openssl32.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-openssl32-macos-10-10
      with:
        path: /usr/local/ssl32
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.cache-openssl32.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Build OpenSSL
      if: steps.cache-openssl32.outputs.cache-hit != 'true'
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.10.0
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        git clone https://github.com/openssl/openssl.git -b OpenSSL_1_1_1-stable
        cd openssl
        KERNEL_BITS=32 ./config --prefix=/usr/local/ssl32
        make
        sudo make install_sw
  buildopenssl64:
    runs-on: macos-latest
    steps:
    - name: Check for openssl
      id: cache-openssl64
      uses: Mystraht/cache@master
      env:
        cache-name: cache-openssl64-macos-10-10
      with:
        path: /usr/local/ssl64
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache openssl
      if: steps.cache-openssl64.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-openssl64-macos-10-10
      with:
        path: /usr/local/ssl64
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.cache-openssl64.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Build OpenSSL
      if: steps.cache-openssl64.outputs.cache-hit != 'true'
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.10.0
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        git clone https://github.com/openssl/openssl.git -b OpenSSL_1_1_1-stable
        cd openssl
        KERNEL_BITS=64 ./config --prefix=/usr/local/ssl64
        sudo make install_sw
  buildopenssl:
    runs-on: macos-latest
    needs: [buildopenssl32, buildopenssl64]
    steps:
    - name: Check openssl
      id: openssl
      uses: Mystraht/cache@master
      env:
        cache-name: cache-openssl-macos-10-10
      with:
        path: /usr/local/ssl
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache openssl32
      if: steps.openssl.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-openssl-macos-10-10
      with:
        path: /usr/local/ssl
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache openssl32
      if: steps.openssl.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-openssl32-macos-10-10
      with:
        path: /usr/local/ssl32
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache openssl64
      if: steps.openssl.cache-hit != 'true'
      uses: actions/cache@v1
      env:
        cache-name: cache-openssl64-macos-10-10
      with:
        path: /usr/local/ssl64
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Build universal lib
      if: steps.openssl.cache-hit != 'true'
      run: |
        mkdir -p /usr/local/ssl/lib
        lipo -create /usr/local/ssl32/lib/libssl.dylib /usr/local/ssl64/lib/libssl.dylib -output /usr/local/ssl64/lib/libssl.dylib
        lipo -create /usr/local/ssl32/lib/libcrypto.dylib /usr/local/ssl64/lib/libcrypto.dylib -output /usr/local/ssl64/lib/libcrypto.dylib
        cd /usr/local/ssl/lib
        install_name_tool -id @rpath/libssl.dylib -add_rpath @loader_path/../Frameworks libssl.dylib
        install_name_tool -id @rpath/libcrypto.dylib -add_rpath @loader_path/../Frameworks libcrypto.dylib
  build:
    runs-on: macos-latest
    needs: [brew-libzip, brew-protobuf, brew-libuv, build-libcxx]
    strategy:
      matrix:
        target: ["10.13.0"]
        include:
          - target: "10.13.0"
            micro: 2
            QT_BASE_URL: http://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5150/
            QT_VERSION_SHORT: 5.15.0
            QT_VERSION: 5.15.0-0-202005140805
            QT_PACKAGE_PREFIX: qt.qt5.5150.
            QT_PACKAGE_SUFFIX: clang_64
            QT_PREBUILT_SUFFIX: -MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64
    steps:
    - name: Set Environment Variables
      run: |
        IFS='/' read -ra REPO <<< "${GITHUB_REPOSITORY}"
        echo "::set-env REPO_USER=${REPO[0]}"
        echo "::set-env REPO_NAME=${REPO[1]}"
        IFS='/' read -ra REF <<< "${GITHUB_REF}"
        echo "::set-env BRANCH_NAME=${REF[2]}"
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Cache libcxx32
      id: libcxx32-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx32-macos-10-10-2
      with:
        path: libcxx32-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx64
      id: libcxx64-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx64-macos-10-10-2
      with:
        path: libcxx64-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx
      id: libcxx-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx-macos-10-10-2
      with:
        path: libcxx-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install python dependencies
      run: pip3 install jinja2 ds_store
    - name: Restore libzip
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-libzip-macos-10-10
      with:
        path: /usr/local/Cellar/libzip
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Restore protobuf
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-protobuf-macos-10-10
      with:
        path: /usr/local/Cellar/protobuf
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Restore libuv
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-libuv-macos-10-10
      with:
        path: /usr/local/Cellar/libuv
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: brew install / link
      run: |
        brew install p7zip automake
        HOMEBREW_NO_AUTO_UPDATE=1 brew unlink libzip
        HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall openssl@1.1 || HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl@1.1
        HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall ossp-uuid || HOMEBREW_NO_AUTO_UPDATE=1 brew install ossp-uuid
        HOMEBREW_NO_AUTO_UPDATE=1 brew link libuv protobuf libzip openssl@1.1 ossp-uuid
    - name: Cache qt
      id: cache-qt
      uses: actions/cache@v1
      env:
        cache-name: cache-qt-macos-${{ matrix.target }}
      with:
        path: qt
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Download Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        export QT_BASE_URL=${{ matrix.QT_BASE_URL }}
        export QT_VERSION_SHORT=${{ matrix.QT_VERSION_SHORT }}
        export QT_VERSION=${{ matrix.QT_VERSION }}
        export QT_PACKAGE_PREFIX=${{ matrix.QT_PACKAGE_PREFIX }}
        export QT_PACKAGE_SUFFIX=${{ matrix.QT_PACKAGE_SUFFIX }}
        export QT_PREBUILT_SUFFIX=${{ matrix.QT_PREBUILT_SUFFIX }}
        ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=${{ matrix.target }}
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        python3 __main__.py --qt-path qt/*/* --update-sparkle-appcast https://github.com/${GITHUB_REPOSITORY}/releases/download/ng.dmg/appcast.xml --update-sparkle-ed-public-key ${{ secrets.SPARKLE_ECDSA_PUB }} --buildangle --version "0.${{ matrix.micro }}.${GITHUB_RUN_NUMBER}" ${{ matrix.extraflags }}
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - name: Generate Dist
      run: |
        DMG_FILENAME="Minecraft_Bedrock_Launcher_0.0.${GITHUB_RUN_NUMBER}_macOS_${{ matrix.target }}.dmg"
        mkdir -p dist
        mv "${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg" "dist/${DMG_FILENAME}"
    - name: Upload Latest
      run: |
        curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_darwin_amd64.zip --output ghr.zip
        unzip ghr.zip
        ./ghr*/ghr -t ${{ secrets.GITHUB_TOKEN }} -u ChristopherHX -r osx-packaging-scripts -replace -prerelease -b "# NO SUPPORT THIS IS A TEST RELEASE" ng.dmg dist/
