name: CI
on:
  push:
    branches:
      - master
    tags-ignore:
      - ng.dmg
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.MacOSX1013sdk }}
    - name: Apply custom patch and Update brew
      working-directory: "/usr/local/Homebrew"
      run: |
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git checkout fork/master
    - name: Install brew dependencies
      run: |
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.12.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall python libzip
        HOMEBREW_NO_AUTO_UPDATE=1 brew install p7zip libuv protobuf
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - uses: actions/setup-python@v1
      with:
        python-version: '2.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified  
    - name: Show python versions
      run: python --version && python2 --version && python3 --version
    - name: Install python dependencies
      run: python3 -m pip install --upgrade pip && pip3 install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.12
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        python3 __main__.py --qt-path qt/*/*/ --update-url https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/version.osx --build-id ${GITHUB_RUN_NUMBER}
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - name: Upload Latest
      run: mkdir -p dist && mv "${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg" dist/Minecraft_Bedrock_Launcher.dmg && echo build_id=${GITHUB_RUN_NUMBER}$'\n'download_url=https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/Minecraft_Bedrock_Launcher.dmg > dist/version.osx && curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_darwin_amd64.zip --output ghr.zip && unzip ghr.zip && ./ghr*/ghr -t ${{ secrets.GITHUB_TOKEN }} -u ChristopherHX -r osx-packaging-scripts -recreate -b "# THIS IS A TEST RELEASE OF THE NG BRANCH CURRENTLY NO SUPPORT FOR THIS DMG" ng.dmg dist/