name: CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  build-libcxx32:
    runs-on: macos-latest
    steps:
    - name: Cache libcxx32
      id: libcxx32-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx32-macos-10-10
      with:
        path: libcxx32-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.libcxx32-llvm.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Build libcxx, libcxxabi, libunwind
      if: steps.libcxx32-llvm.outputs.cache-hit != 'true'
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.10.0
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        git clone https://github.com/llvm/llvm-project.git llvm
        mkdir -p libcxx32-build
        cd libcxx32-build
        cmake ../llvm/llvm -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi;libunwind" -DLIBCXX_CXX_ABI=libcxxabi -DLIBCXXABI_USE_LLVM_UNWINDER=ON -DCMAKE_BUILD_TYPE=Release -DLIBCXX_BUILD_32_BITS=ON -DLIBCXXABI_BUILD_32_BITS=ON -DLIBUNWIND_BUILD_32_BITS=ON -DLLVM_BUILD_32_BITS=ON
        make -j4 cxx cxxabi unwind
  build-libcxx64:
    runs-on: macos-latest
    steps:
    - name: Cache libcxx64
      id: libcxx64-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx64-macos-10-10
      with:
        path: libcxx64-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.libcxx64-llvm.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Build libcxx, libcxxabi, libunwind
      if: steps.libcxx64-llvm.outputs.cache-hit != 'true'
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.10.0
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        git clone https://github.com/llvm/llvm-project.git llvm
        mkdir -p libcxx64-build
        cd libcxx64-build
        cmake ../llvm/llvm -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi;libunwind" -DLIBCXX_CXX_ABI=libcxxabi -DLIBCXXABI_USE_LLVM_UNWINDER=ON -DCMAKE_BUILD_TYPE=Release
        make -j4 cxx cxxabi unwind
  build-libcxx:
    runs-on: macos-latest
    needs: [build-libcxx32,build-libcxx64]
    steps:
    - name: Cache libcxx32
      id: libcxx32-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx32-macos-10-10
      with:
        path: libcxx32-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx64
      id: libcxx64-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx64-macos-10-10
      with:
        path: libcxx64-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx
      id: libcxx-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx-3-macos-10-10
      with:
        path: libcxx-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Build universal lib
      if: steps.libcxx-llvm.outputs.cache-hit != 'true'
      run: |
        mkdir -p libcxx-build/
        lipo -create libcxx32-build/lib/libc++.dylib libcxx64-build/lib/libc++.dylib -output libcxx-build/libc++.1.dylib
        lipo -create libcxx32-build/lib/libc++abi.dylib libcxx64-build/lib/libc++abi.dylib -output libcxx-build/libc++abi.1.dylib
        lipo -create libcxx32-build/lib/libunwind.dylib libcxx64-build/lib/libunwind.dylib -output libcxx-build/libunwind.1.dylib
        cd libcxx-build
        ln -s libc++.1.dylib libc++.dylib
        ln -s libc++abi.1.dylib libc++abi.dylib
        ln -s libunwind.1.dylib libunwind.dylib
        install_name_tool -rpath @loader_path/../lib @loader_path/../Frameworks libc++.dylib
        install_name_tool -rpath @loader_path/../lib @loader_path/../Frameworks libc++abi.dylib
        install_name_tool -rpath @loader_path/../lib @loader_path/../Frameworks libunwind.dylib
  brew-deps:
    runs-on: macos-latest
    steps:
    - name: Cache brew Cellar
      id: cache-brew-cellar
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-macos-cellar-10-10
      with:
        path: /usr/local/Cellar/
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - uses: actions/checkout@v1
      if: steps.cache-brew-cellar.outputs.cache-hit != 'true'
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Apply custom patch and Update brew
      if: steps.cache-brew-cellar.outputs.cache-hit != 'true'
      working-directory: "/usr/local/Homebrew"
      run: |
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git checkout fork/master
    - name: Install brew dependencies
      if: steps.cache-brew-cellar.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install p7zip automake sphinx-doc
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.10.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall python libzip
        HOMEBREW_NO_AUTO_UPDATE=1 brew install libuv protobuf
  build:
    runs-on: macos-latest
    needs: [brew-deps, build-libcxx]
    steps:
    - name: Set Environment Variables
      run: |
        IFS='/' read -ra REPO <<< "${GITHUB_REPOSITORY}"
        echo "::set-env REPO_USER=${REPO[0]}"
        echo "::set-env REPO_NAME=${REPO[1]}"
        IFS='/' read -ra REF <<< "${GITHUB_REF}"
        echo "::set-env BRANCH_NAME=${REF[2]}"
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1014sdk }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Download old dmg's
      run: |
        mkdir -p sparcle/
        git clone https://github.com/ChristopherHX/github-release-downloader.git grd
        cd grd
        npm install
        npm run-script build
        cd ..
        grd/bin/grd --token ${{ secrets.GITHUB_TOKEN }} --owner ChristopherHX --repository osx-packaging-scripts --filter-asset '^.*\.dmg$' --match-version 'ng_10.10\.dmg' --output sparcle/
        mv sparcle/${GITHUB_REPOSITORY}/ng_10.10.dmg/*.dmg sparcle/ || :
    - name: Cache libcxx32
      id: libcxx32-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx32-macos-10-10
      with:
        path: libcxx32-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx64
      id: libcxx64-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx64-macos-10-10
      with:
        path: libcxx64-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache libcxx
      id: libcxx-llvm
      uses: actions/cache@v1
      env:
        cache-name: cache-libcxx-3-macos-10-10
      with:
        path: libcxx-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install python dependencies
      run: python3 -m pip install --upgrade pip && pip3 install jinja2 ds_store
    - name: Cache brew Cellar
      id: cache-brew-cellar
      uses: actions/cache@v1
      env:
        cache-name: cache-brew-macos-cellar-10-10
      with:
        path: /usr/local/Cellar/
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: brew link
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew unlink libzip
        HOMEBREW_NO_AUTO_UPDATE=1 brew link libuv protobuf libzip p7zip automake cmake
    - name: Cache qt
      id: cache-qt
      uses: actions/cache@v1
      env:
        cache-name: cache-qt-macos-10-10
      with:
        path: qt
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Download Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.10.0
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        python3 __main__.py --qt-path qt/*/* --update-sparkle-appcast https://github.com/${GITHUB_REPOSITORY}/releases/download/ng_10.10.dmg/appcast.xml --update-sparkle-ed-public-key ${{ secrets.SPARKLE_ECDSA_PUB }} --version "0.0.${GITHUB_RUN_NUMBER}"
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - name: Generate Dist
      run: |
        DMG_FILENAME="Minecraft_Bedrock_Launcher.0.0.${GITHUB_RUN_NUMBER}.dmg"
        mv "${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg" "sparcle/${DMG_FILENAME}"
        qt/*/*/bin/generate_appcast -s ${{ secrets.SPARKLE_ECDSA }} sparcle/
        mkdir -p dist
        sed 's/\%20/./g' sparcle/appcast.xml > dist/appcast.xml
        mv sparcle/*.delta dist/|| :
        mv "sparcle/${DMG_FILENAME}" dist/
        echo build_id=${GITHUB_RUN_NUMBER}$'\n'download_url=https://github.com/${GITHUB_REPOSITORY}/releases/download/ng_10.10.dmg/Minecraft_Bedrock_Launcher.dmg > dist/version.osx
    - name: Upload Latest
      run: |
        curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_darwin_amd64.zip --output ghr.zip
        unzip ghr.zip
        ./ghr*/ghr -t ${{ secrets.GITHUB_TOKEN }} -u ChristopherHX -r osx-packaging-scripts -replace -prerelease -b "# NO SUPPORT THIS IS A TEST RELEASE" ng_10.10.dmg dist/
